structure(list(url = "https://api.datawrapper.de/v3/charts", 
    status_code = 201L, headers = structure(list(date = "Sun, 24 Nov 2019 17:31:33 GMT", 
        `content-type` = "application/json; charset=utf-8", `content-length` = "227", 
        connection = "keep-alive", vary = "origin", `access-control-allow-credentials` = "true", 
        `access-control-expose-headers` = "WWW-Authenticate,Server-Authorization", 
        `cache-control` = "no-cache", `strict-transport-security` = "max-age=15768000", 
        `strict-transport-security` = "max-age=15768000", `cf-cache-status` = "DYNAMIC", 
        `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
        server = "cloudflare", `cf-ray` = "53ad1dfe5fa87cdc-MUC"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 201L, version = "HTTP/1.1", 
        headers = structure(list(date = "Sun, 24 Nov 2019 17:31:33 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            `content-length` = "227", connection = "keep-alive", 
            vary = "origin", `access-control-allow-credentials` = "true", 
            `access-control-expose-headers` = "WWW-Authenticate,Server-Authorization", 
            `cache-control` = "no-cache", `strict-transport-security` = "max-age=15768000", 
            `strict-transport-security` = "max-age=15768000", 
            `cf-cache-status` = "DYNAMIC", `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
            server = "cloudflare", `cf-ray` = "53ad1dfe5fa87cdc-MUC"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_.datawrapper.de", 
        flag = TRUE, path = "/", secure = FALSE, expiration = structure(1577208691, class = c("POSIXct", 
        "POSIXt")), name = "__cfduid", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"title\":\"\",\"theme\":\"default\",\"type\":\"d3-bars\",\"language\":\"en-US\",\"metadata\":{\"data\":{}},\"authorId\":66969,\"id\":\"Kqysh\",\"lastModifiedAt\":\"2019-11-24T17:31:33.624Z\",\"createdAt\":\"2019-11-24T17:31:33.624Z\",\"url\":\"/v3/charts/Kqysh\"}"), 
    date = structure(1574616693, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 6e-05, 
    connect = 6.3e-05, pretransfer = 0.000178, starttransfer = 0.168931, 
    total = 0.168962)), class = "response")
